# Generated by Django 4.2.6 on 2023-11-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('gst_no', models.CharField(max_length=15)),
                ('fssai_code', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
    ]
