# Generated by Django 4.2.6 on 2023-10-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('business_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('gst_no', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=15)),
                ('registration_date', models.DateField()),
                ('speciality', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
