# Generated by Django 4.2.6 on 2023-10-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('gst_no', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=15)),
                ('registration_date', models.DateField()),
                ('speciality', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
            ],
        ),
    ]
