# Generated by Django 4.2.6 on 2023-10-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='default_user_name', max_length=50, unique=True),
        ),
    ]
