# Generated by Django 4.2.6 on 2023-10-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='speciality',
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='9000000000', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='default_user_id', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
