# Generated by Django 4.2.6 on 2023-10-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, null=True),
        ),
    ]
