# Generated by Django 4.2.6 on 2023-11-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gst_no',
        ),
    ]
