# Generated by Django 4.2.6 on 2023-10-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gst_no',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(),
        ),
    ]
