# Generated by Django 4.2.6 on 2023-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='defaultexample@example.com', max_length=254, unique=True),
        ),
    ]
